name: audit_tracker
description: "Audit Tracker web app is developed for DILG Marinduque."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  fluttertoast: ^8.2.2
  firebase_database: ^10.2.7
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.9.3
  firebase_core: ^2.0.7
  crypto: ^3.0.3
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  image: ^4.1.3
  intl: ^0.19.0
  pointycastle: ^3.7.4
  file_picker: ^8.0.0+1
  mime_type: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo_rounded.png
    - assets/app_logo_sharp.png
    - assets/dilg_logo.png
    - assets/key.png
    - assets/user.png
    - assets/email.png
    - assets/arrow_right.png
    - assets/manual.png
    - assets/about.png
    - assets/logout.png
    - assets/background.png
    - assets/camera_icon.png
    - assets/gallery_icon.png
    - assets/forms.png
    - assets/calendar.png
    - assets/upload.png